#!/usr/bin/env node
import 'dotenv/config'
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js'
import fetch from 'node-fetch'

const API_URL = (process.env.BASELY_API_URL ?? '').replace(/\/$/, '')
const API_KEY = process.env.BASELY_API_KEY ?? ''

if (!API_URL || !API_KEY) {
  console.error('BASELY_API_URL and BASELY_API_KEY must be set')
  process.exit(1)
}

async function request(method: string, path: string, body?: unknown) {
  const res = await fetch(`${API_URL}${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${API_KEY}`,
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  const data = await res.json() as any
  if (!res.ok) throw new Error(data.error ?? res.statusText)
  return data
}

const PG_TO_TS: Record<string, string> = {
  'integer': 'number', 'bigint': 'number', 'smallint': 'number',
  'numeric': 'number', 'real': 'number', 'double precision': 'number',
  'boolean': 'boolean',
  'text': 'string', 'varchar': 'string', 'character varying': 'string',
  'char': 'string', 'uuid': 'string',
  'json': 'Record<string, unknown>', 'jsonb': 'Record<string, unknown>',
  'timestamp with time zone': 'string', 'timestamp without time zone': 'string',
  'timestamptz': 'string', 'date': 'string', 'time': 'string',
  'bytea': 'Buffer',
}

function genTypes(projectId: string, tables: Record<string, { column: string; type: string; nullable: boolean; default: string | null }[]>): string {
  const lines = [
    `// Generated by dbforge — project: ${projectId}`,
    '',
  ]
  for (const [tableName, cols] of Object.entries(tables)) {
    const iface = tableName.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')
    lines.push(`export interface ${iface} {`)
    for (const col of cols) {
      const tsType = PG_TO_TS[col.type.toLowerCase()] ?? 'unknown'
      const optional = col.nullable || col.default !== null ? '?' : ''
      lines.push(`  ${col.column}${optional}: ${tsType}${col.nullable ? ' | null' : ''}`)
    }
    lines.push('}', '')
  }
  return lines.join('\n')
}

const server = new Server(
  { name: 'dbforge', version: '0.1.0' },
  { capabilities: { tools: {} } }
)

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: 'create_project',
      description: 'Provision a new Postgres database project. Returns a connection string ready to use.',
      inputSchema: {
        type: 'object',
        properties: {
          id: { type: 'string', description: 'Optional project ID (lowercase alphanumeric). Auto-generated if omitted.' },
        },
      },
    },
    {
      name: 'delete_project',
      description: 'Delete a project and permanently drop its schema and all data.',
      inputSchema: {
        type: 'object',
        required: ['id', 'connectionString'],
        properties: {
          id: { type: 'string' },
          connectionString: { type: 'string' },
        },
      },
    },
    {
      name: 'execute_sql',
      description: 'Execute SQL against a project. Use for queries, inserts, DDL. Returns rows.',
      inputSchema: {
        type: 'object',
        required: ['projectId', 'connectionString', 'sql'],
        properties: {
          projectId: { type: 'string' },
          connectionString: { type: 'string' },
          sql: { type: 'string' },
          params: { type: 'array', description: 'Positional query parameters ($1, $2, ...)' },
        },
      },
    },
    {
      name: 'get_schema',
      description: 'Introspect the database schema — returns all tables and their columns with types. Call this before writing queries to understand the data model.',
      inputSchema: {
        type: 'object',
        required: ['projectId'],
        properties: {
          projectId: { type: 'string' },
        },
      },
    },
    {
      name: 'apply_migration',
      description: 'Apply a named SQL migration to a project. Idempotent — will error if already applied. Use for schema changes.',
      inputSchema: {
        type: 'object',
        required: ['projectId', 'connectionString', 'name', 'sql'],
        properties: {
          projectId: { type: 'string' },
          connectionString: { type: 'string' },
          name: { type: 'string', description: 'Unique migration name e.g. "001_create_users"' },
          sql: { type: 'string', description: 'The SQL to run' },
        },
      },
    },
    {
      name: 'list_migrations',
      description: 'List all applied migrations for a project in order.',
      inputSchema: {
        type: 'object',
        required: ['projectId', 'connectionString'],
        properties: {
          projectId: { type: 'string' },
          connectionString: { type: 'string' },
        },
      },
    },
    {
      name: 'gen_types',
      description: 'Generate TypeScript interfaces from the project schema. Returns a .ts file string ready to save.',
      inputSchema: {
        type: 'object',
        required: ['projectId'],
        properties: {
          projectId: { type: 'string' },
        },
      },
    },
  ],
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params as { name: string; arguments: any }

  try {
    let result: any

    switch (name) {
      case 'create_project':
        result = await request('POST', '/projects', args.id ? { id: args.id } : {})
        break

      case 'delete_project':
        result = await request('DELETE', `/projects/${args.id}`)
        break

      case 'execute_sql':
        result = await request('POST', `/projects/${args.projectId}/query`, {
          connectionString: args.connectionString,
          sql: args.sql,
          params: args.params,
        })
        break

      case 'get_schema':
        result = await request('GET', `/projects/${args.projectId}/schema`)
        break

      case 'apply_migration':
        result = await request('POST', `/projects/${args.projectId}/migrations`, {
          connectionString: args.connectionString,
          name: args.name,
          sql: args.sql,
        })
        break

      case 'list_migrations':
        result = await request(
          'GET',
          `/projects/${args.projectId}/migrations?connectionString=${encodeURIComponent(args.connectionString)}`
        )
        break

      case 'gen_types': {
        const schemaResult = await request('GET', `/projects/${args.projectId}/schema`)
        result = genTypes(args.projectId, schemaResult.tables)
        return { content: [{ type: 'text', text: result }] }
      }

      default:
        throw new Error(`Unknown tool: ${name}`)
    }

    return {
      content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
    }
  } catch (err: any) {
    return {
      content: [{ type: 'text', text: `Error: ${err.message}` }],
      isError: true,
    }
  }
})

const transport = new StdioServerTransport()
await server.connect(transport)
